version: "3.3"

services:

  vote:
    image: deon/vote:latest
    container_name: vote.example.com
    build: .
    ports:
      - "8002:8002"
    networks:
      - net_deon
    volumes:
      - type: bind
        source: ~/deon/fabric-samples/first-network/channel-artifacts
        target: /config/channel-artifacts
        read_only: true
      - type: bind
        source: ~/deon/fabric-samples/first-network/crypto-config
        target: /config/crypto-config
        read_only: true
      - type: volume
        source: state-store
        target: /tmp/state-store

networks:
  net_deon:
    external: true

volumes:
  state-store:
    external:
      name: core-service_state-store