version: "3.3"

services:

  deon:
    image: deon/vote:latest
    container_name: vote.example.com
    build: .
    ports:
      - "8000:8000" 
    networks:
      - net_byfn
    volumes:
      - "~/deon/fabric-samples/first-network/channel-artifacts:/config/channel-artifacts:ro"
      - "~/deon/fabric-samples/first-network/crypto-config:/config/crypto-config:ro"
  #   depends_on:
  #     - ipfs

  # ipfs:
  #   image: ipfs/go-ipfs:latest
  #   container_name: ipfs.node.example.com
  #   ports:
  #     - "8080:8080"
  #     - "4001:4001"
  #     - "5001:5001"
  #   volumes:
  #     - "/tmp/ipfs-docker-staging:/export"
  #     - "/tmp/ipfs-docker-data:/data/ipfs"
  #   networks:
  #     - net_byfn

networks:
  net_byfn:
    external: true