version: "3.3"

services:

  deon:
    image: deonproject/core-service:latest
    container_name: deon.example.com
    ports:
      - "8000:8000"
    networks:
      - net_deon
    volumes:
      - type: bind
        source: ../../off-grid-net/channel-artifacts
        target: /config/channel-artifacts
        read_only: true
      - type: bind
        source: ../../off-grid-net/crypto-config
        target: /config/crypto-config
        read_only: true
      - type: volume
        source: state-store
        target: /tmp/state-store
    command: /bin/start http://${DOCKERHOST}:9000
    depends_on:
      - ipfs
      - admin
      - client

  vote:
    image: deonproject/vote:latest
    container_name: vote.example.com
    ports:
      - "8001:8001"
    networks:
      - net_deon
    volumes:
      - type: bind
        source: ../../off-grid-net/channel-artifacts
        target: /config/channel-artifacts
        read_only: true
      - type: bind
        source: ../../off-grid-net/crypto-config
        target: /config/crypto-config
        read_only: true
      - type: bind
        source: ~/deon/fabric-sdk-go
        target: /deon/fabric-sdk-go
        read_only: true
      - type: volume
        source: state-store
        target: /tmp/state-store
    depends_on:
      - deon

  admin:
    image: deonproject/aries-cloudagent-run:latest
    container_name: admin.example.com
    ports:
      - "8020-8027:8020-8027"
    networks:
      - net_deon
    command: >
      start 
      --endpoint http://${DOCKERHOST}:8020 
      --label admin 
      --auto-ping-connection 
      --auto-respond-messages 
      --auto-store-credential 
      --auto-accept-invites 
      --auto-accept-requests 
      --auto-verify-presentation 
      --inbound-transport http 0.0.0.0 8020 
      --outbound-transport http 
      --admin 0.0.0.0 8021 
      --admin-insecure-mode 
      --genesis-url http://${DOCKERHOST}:9000/genesis 
      --wallet-type indy 
      --wallet-name admin001 
      --wallet-key admin001 

  client:
    image: deonproject/aries-cloudagent-run:latest
    container_name: client.example.com
    ports:
      - "8030-8037:8030-8037"
    networks:
      - net_deon
    command: >
      start 
      --endpoint http://${DOCKERHOST}:8030 
      --label client 
      --auto-ping-connection 
      --auto-respond-messages 
      --auto-store-credential 
      --auto-accept-invites 
      --auto-accept-requests 
      --auto-respond-credential-offer
      --auto-respond-presentation-request 
      --inbound-transport http 0.0.0.0 8030 
      --outbound-transport http 
      --admin 0.0.0.0 8031 
      --admin-insecure-mode 
      --genesis-url http://${DOCKERHOST}:9000/genesis 
      --wallet-type indy 
      --wallet-name client001 
      --wallet-key client001 

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs.node.example.com
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - "/tmp/ipfs-docker-staging:/export"
      - "/tmp/ipfs-docker-data:/data/ipfs"
    networks:
      - net_deon

networks:
  net_deon:
    external: true

volumes:
  state-store:
